// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adubcuczwckqxrofzvpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkdWJjdWN6d2NrcXhyb2Z6dnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3OTYxMTgsImV4cCI6MjA1MjM3MjExOH0.tV0J9Vh-fJsntngmdj0T8igaTm2RELMEqWhtWij7Z4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);